on:
    push:
        branches:
            - main

jobs:
    contrib-readme-job:
        runs-on: ubuntu-latest
        name: A job to automate contributors in credits.md
        permissions:
          contents: write
          pull-requests: write
        steps:
            - name: Contributor List
              uses: akhilmhdh/contributors-readme-action@v2.3.11
              with:
                readme_path: "docs/credits.md"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}